const assert=require('assert');
const g=require('./drawing-production-authority-gate');
const pass={SOURCE:'PASS',GEOMETRY:'PASS',FACT:'PASS',SEMANTIC:'PASS',REFERENCE_EFFECT:'PASS',ARCHITECTURAL_READABILITY:'PASS',USER_EFFECT:'PASS'};
assert.equal(g.evaluate({artifact_class:'FINAL',execution_route:'AUTHORIZED_ENGINE',engine_id:'DRAWING_ENGINE_V2',operations:['VECTOR_STYLE_LAYER'],gates:pass}).decision,'SHOW');
assert.equal(g.evaluate({artifact_class:'FINAL',execution_route:'ONE_OFF_SCRIPT',one_off:true,gates:pass}).decision,'HOLD');
assert.equal(g.evaluate({artifact_class:'PREVIEW',execution_route:'AUTHORIZED_ENGINE',engine_id:'DRAWING_ENGINE_V2',operations:['DESTRUCTIVE_RASTER_MASK'],gates:pass}).decision,'HOLD');
assert.equal(g.evaluate({artifact_class:'USER_FACING',execution_route:'AUTHORIZED_ENGINE',engine_id:'DRAWING_ENGINE_V2',operations:['GENERATIVE_GEOMETRY_REDRAW'],gates:pass}).decision,'HOLD');
assert.equal(g.evaluate({artifact_class:'USER_FACING',execution_route:'AUTHORIZED_ENGINE',engine_id:'DRAWING_ENGINE_V2',operations:['VECTOR_STYLE_LAYER'],gates:{...pass,REFERENCE_EFFECT:'FAIL'}}).decision,'HOLD');
assert.equal(g.evaluate({artifact_class:'DIAGNOSTIC',user_exposure:true}).decision,'HOLD');
assert.equal(g.evaluate({artifact_class:'FINAL',execution_route:'AUTHORIZED_ENGINE',engine_id:'DRAWING_ENGINE_V2',operations:['VECTOR_STYLE_LAYER'],gates:pass,narrative_present:true}).decision,'HOLD');
console.log('drawing-production-authority-gate: PASS');
